name: JARTICリアルタイム自動同期システム

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4

    - name: JARTICの交通規制データをクリーンに回収
      run: |
        curl -s -H "Accept: application/json" "https://www.jartic.or.jp/geo/v1/hokkaido/freeway/features.json" > data.json

    - name: 最新データをGitHubリポジトリへ自動書き込み
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add data.json
        git commit -m "【運行管制】本物の初期安定版仕入れルートへ完全復旧" || exit 0
        git push
